#!/usr/bin/expect

set IP [lindex $argv 0]
set User [lindex $argv 1]
set pass [lindex $argv 2]

if {3 != [llength $argv]} {
    puts "USAGE < ssh host user pass >"
    exit 1
}

spawn ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $User@$IP "ifconfig; exit"

expect "assword:"
send "$pass\r"
interact
